#### 1. Import Libraries

In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### 2. Define Environment

In [2]:
ENVIRONMENT = "Loan Approval System"

print(f"Environment : {ENVIRONMENT}")

Environment : Loan Approval System

#### 3. Define States

In [3]:
states = {
    0: "Low Risk",
    1: "Medium Risk",
    2: "High Risk"
}

n_states = len(states)
print(states)

{0: 'Low Risk', 1: 'Medium Risk', 2: 'High Risk'}

#### 4. Define Actions

In [4]:
actions = {
    0: "Approve",
    1: "Review",
    2: "Reject"
}

n_actions = len(actions)
print(actions)

{0: 'Approve', 1: 'Review', 2: 'Reject'}

#### 5. Define Reward Matrix

In [5]:
reward_matrix = np.array([
    # Approve, Review, Reject
    [100, 40, -20],    # Low Risk
    [20, 60, 10],    # Medium Risk
    [-300, 20, 100]     # High Risk
])

reward_df = pd.DataFrame(
    reward_matrix,
    index=states.values(),
    columns=actions.values()
)

display(reward_df)

             Approve  Review  Reject
Low Risk         100      40     -20
Medium Risk       20      60      10
High Risk       -300      20     100

#### 6. Initialize Q Table

In [6]:
q_table = np.zeros(
    (n_states, n_actions)
)

q_df = pd.DataFrame(
    q_table,
    index=states.values(),
    columns=actions.values()
)

display(q_df)

             Approve  Review  Reject
Low Risk         0.0     0.0     0.0
Medium Risk      0.0     0.0     0.0
High Risk        0.0     0.0     0.0

#### 7. Hyperparameters

In [7]:
ALPHA = 0.10 # Learning Rate
GAMMA = 0.90 # Discount Factor
EPSILON = 1.00 # Exploration Rate
EPSILON_DECAY = 0.995 
MIN_EPSILON = 0.01 
EPISODES = 5000

#### 8. Environment Function

In [8]:
def step(state, action):

    # Get reward
    reward = reward_matrix[state, action]

    # Simulate next customer (temporary)
    next_state = np.random.randint(0, n_states)

    return next_state, reward

#### 9. Epsilon Greedy Policy

In [9]:
def choose_action(state, epsilon):

    # Exploration
    if np.random.rand() < epsilon:

        return np.random.randint(n_actions)

    # Exploitation
    return np.argmax(q_table[state])

#### 10. Update Q Table

In [10]:
def update_q_table(
    state,
    action,
    reward,
    next_state
):

    old_value = q_table[state, action]

    next_max = np.max(
        q_table[next_state]
    )

    new_value = old_value + ALPHA * (
        reward +
        GAMMA * next_max -
        old_value
    )

    q_table[state, action] = new_value

#### 11. Training Function

In [11]:
def train():

    epsilon = EPSILON
    reward_history = []

    for episode in range(EPISODES):

        # Random starting customer
        state = np.random.randint(n_states)

        total_reward = 0

        # One decision per episode
        action = choose_action(
            state,
            epsilon
        )

        next_state, reward = step(
            state,
            action
        )

        update_q_table(
            state,
            action,
            reward,
            next_state
        )

        total_reward += reward

        reward_history.append(
            total_reward
        )

        # Reduce exploration gradually
        epsilon = max(
            MIN_EPSILON,
            epsilon * EPSILON_DECAY
        )

    return reward_history

In [12]:
# 12. Final Q Table
print("\nFinal Q Table")
q_df = pd.DataFrame(
    np.round(q_table, 2),
    index=states.values(),
    columns=actions.values()
)

print(q_df)

Final Q Table
             Approve  Review  Reject
Low Risk         0.0     0.0     0.0
Medium Risk      0.0     0.0     0.0
High Risk        0.0     0.0     0.0

In [13]:
# 13. Learned Policy
print("\nLearned Policy")

for state in range(n_states):

    best_action = np.argmax(q_table[state])

    print(
        f"{states[state]} "
        f"-> "
        f"{actions[best_action]}"
    )

Learned Policy
Low Risk -> Approve
Medium Risk -> Approve
High Risk -> Approve

In [15]:
def evaluate_agent():

    print("AGENT DECISIONS")

    for state in range(n_states):

        action = np.argmax(q_table[state])

        reward = reward_matrix[state, action]

        print(
            f"{states[state]:15}"
            f" -> "
            f"{actions[action]:10}"
            f" Reward = {reward}"
        )

evaluate_agent()

AGENT DECISIONS
Low Risk        -> Approve    Reward = 100
Medium Risk     -> Approve    Reward = 20
High Risk       -> Approve    Reward = -300